FROM golang:1.19-alpine
WORKDIR /app

COPY ../internal/payment_service/go.mod .
COPY ../internal/payment_service/go.sum .

RUN go mod download

COPY ../internal/payment_service .
COPY ../internal/shared /usr/local/go/src/chatvo/shared

RUN go build -o main .

CMD ["./main"]
